# Generated by Django 5.1.6 on 2025-02-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('bid_px', models.CharField(max_length=20)),
                ('bid_qty', models.CharField(max_length=20)),
                ('ask', models.CharField(max_length=20)),
                ('ask_qty', models.CharField(max_length=20)),
                ('last_px', models.CharField(max_length=20)),
                ('volume', models.CharField(max_length=20)),
                ('close_px', models.CharField(max_length=20)),
                ('market_status', models.CharField(max_length=20)),
                ('timestamp', models.CharField(max_length=20)),
            ],
        ),
    ]
